### ISSUE TITLE
PE creates an error (which isn't pretty)

### ISSUE THREAD

**Issue by vrescobar** [eproxus/pretty_errors#1]
Hello,

I am running an example in Erlang 17.3, under OSX, I decided to try Pretty Errors because I find the default stack trace quite hard to read (and isn't any default printer for it?). So I decided to try the default usage you suggest in git but it causes yet another stack trace (also not pretty).

```  
{"init terminating in do_boot",{{badmatch,{init,start_it,1,[]}},[{pretty_errors,stacktrace_pretty,2,[{file,"src/pretty_errors.erl"},{line,18}]},{pretty_errors,stacktrace_pretty,2,[{file,"src/pretty_errors.erl"},{line,33}]},{proof_sup,start_link,0,[{file,"src/proof_sup.erl"},{line,20}]},{proof_app,start,2,[{file,"src/proof_app.erl"},{line,13}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,657}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
~~~ 
```

**Comment by eproxus** [comment]
Could you post the actual stack trace you are trying to print?

**Comment by vrescobar** [comment]
That was 7 months ago. I stopped using pretty errors long long ago.
